InstallerConfig
drorwolmer/tsinstaller pull request #6
Opened 2021-11-17 10:28 UTC by leebm3

2021-11-17 11:54 UTC, drorwolmer requested changes

2021-11-17 11:54 UTC, drorwolmer commented on lib/installer.ts
> +    logger.logToFile(JSON.stringify({...{"title" : title}, ...res}, null));
```js
{title, ...res}
```

2021-11-18 08:17 UTC, drorwolmer commented on lib/logsHandler.ts
> +        appendFileSync(this.logPath(), `[INFO] ${new Date().toISOString()} ${message}\n`)
no need to call `logpath()` every time `logToFile()` is called, it should be calculated on the constructor

2021-11-18 11:22 UTC, leebm3 commented
@drorwolmer 
Added the proxy Validation step if proxy wasn't set correctly in env.
Added proxy get from env

2021-11-18 14:37 UTC, drorwolmer requested changes
also make sure you use `prettier` on all this stuff

2021-11-18 14:37 UTC, drorwolmer commented on lib/network.ts
> +import { env } from 'process';
unneeded

2021-11-21 08:24 UTC, drorwolmer commented on lib/logsHandler.ts
> +        this.pathToLogFile = join(tmpdir(), this.name)
`this.name` is not really needed, just the `filepath` attribute is used (internally)
refactor this

2021-11-21 09:25 UTC, drorwolmer approved these changes

2021-11-21 09:26 UTC, merged